### ISSUE TITLE
Don't store demo page titles as filename

### ISSUE THREAD

**Issue by edg2s** [MatmaRex/patchdemo#129]
As discussed when this feature was merged (#95) there are problems with storing the page title as the filename:
* Windows doesn't like colons `:` and probably other punctuation that is valid in a page title
* All OSes won't allow `/` in a filename, i.e. subpages

Other options:
* Use a descriptive filename, then store the title in the first line of the file
  * Easy to read/create
  * Requires a more complex script to import
* Use the [[Special:Export]] XML format
  * Can be imported using existing scripts
  * Can store author/page history if required

cc @catrope @MatmaRex

**Comment by MatmaRex** [comment]
The export XML format would be fine by me, the only drawback is that it's annoying to edit by hand, since you have to deal with entities.

**Comment by MatmaRex** [comment]
I don't really care though, I'm fine with the current approach, or with whatever you want to propose.
