### ISSUE TITLE
Automatically announce new wikis on Phabricator and/or Gerrit

### ISSUE THREAD

**Issue by edg2s** [MatmaRex/patchdemo#144]
For example, a `patchdemobot` account could post the following on linked Phab tasks:

> Matmarex created a wiki with patches linked to this task at https://patchdemo.wmflabs.org/...

This would improve visibility to non technical users watching the task.

The feature could be disabled via a checkbox in the form.

**Comment by edg2s** [comment]
@MatmaRex if approach #145 seems sensible, we can start the process for requesting a bot: https://www.mediawiki.org/wiki/Phabricator/Bots

**Comment by MatmaRex** [comment]
The approach seems sensible but I'm not sure if this is always wanted. I could see someone hesitating to create a demo because they don't want to spam the associated task. Could we make this an optional checkbox?

**Comment by edg2s** [comment]
Yeah - I mentioned this in the original description, have added a commit which implements it.

**Comment by edg2s** [comment]
Filed a bot request: https://phabricator.wikimedia.org/T265418

**Comment by edg2s** [comment]
Bot created. I've added the key (private link for reference: https://phabricator.wikimedia.org/P12992) to the server, so should be ready for deployment.

**Comment by MatmaRex** [comment]
Thanks, looks cool.
