### ISSUE TITLE
Link to FAQ in banner message

### ISSUE THREAD

**Issue by edg2s** [MatmaRex/patchdemo#147]
Link: https://github.com/MatmaRex/patchdemo#faq

Current message:
Any wiki created with this tool may be deleted at any time along with all the content on it, so you should not rely on them being available, or use them to store important information.

Append:
For more information please see our [FAQ](https://github.com/MatmaRex/patchdemo#faq).

**Comment by MatmaRex** [comment]
Thanks, I added it to the banner on https://patchdemo.wmflabs.org/.
