### ISSUE TITLE
rdfind in deduplicate.sh is getting slow, make it a cron job

### ISSUE THREAD

**Issue by edg2s** [MatmaRex/patchdemo#165]
It takes several minutes to run on the full wikis folder, and all it does is free up some disk space.

**Comment by edg2s** [comment]
Alternatively I suggested we just run rdfind against the newly created directory and the repositories folder. What files would be missed if we did this?

**Comment by MatmaRex** [comment]
> Alternatively I suggested we just run rdfind against the newly created directory and the repositories folder. What files would be missed if we did this?

Definitely don't do that. If some files in wikis/ and repos/ become hardlinks to the same data, then changing the ones in repos/ (i.e. updating the repositories) would also update the copies in wikis/, which could then break the wiki in confusing ways if only some of the files are changed.

We could run rdfind only against the newly created directory and e.g. the previously created wiki, I'm not sure how well that would work, but it won't break anything.

**Comment by MatmaRex** [comment]
As discussed on #167, this does not work. I'm going to revert it unless you plan on working on it more.

**Comment by MatmaRex** [comment]
Actually, I tried to fix it: https://github.com/MatmaRex/patchdemo/pull/173

**Comment by MatmaRex** [comment]
Still doesn't work.

**Comment by edg2s** [comment]
https://github.com/MatmaRex/patchdemo/pull/173#issuecomment-721846955

**Comment by MatmaRex** [comment]
> Neat. If this doesn't work we can just go with my original plan which is to document "Add a cron job" in the README.

I don't see how that helps me in getting it working on <https://patchdemo.wmflabs.org/>.

**Comment by edg2s** [comment]
just add a root cronjob the traditional way (`sudo crontab -e`)

**Comment by MatmaRex** [comment]
I'm not going to do anything manually when setting up new instances. And I also wouldn't expect that to "just work" either.

**Comment by MatmaRex** [comment]
Finally it works.

Before: https://github.com/MatmaRex/patchdemo/pull/167#issuecomment-718958165

> ```
> matmarex@patchdemo:/var/www/html$ du -sh wikis/c3058b39da82d3c238a3ab3972ded2cc wikis/6f7b4fe31f8353e49cb49f5488cd3807
> 392M    wikis/c3058b39da82d3c238a3ab3972ded2cc
> 392M    wikis/6f7b4fe31f8353e49cb49f5488cd3807
> ```
> 
> I am expecting one of them to drop to ~0 after the deduplicate job runs.

Now it has finally deduplicated them: (and also deduplicated 27 MB of files within the wiki, interesting, I've never even noticed that)
```
matmarex@patchdemo:/var/www/html$ du -sh wikis/c3058b39da82d3c238a3ab3972ded2cc wikis/6f7b4fe31f8353e49cb49f5488cd3807
365M    wikis/c3058b39da82d3c238a3ab3972ded2cc
9.7M    wikis/6f7b4fe31f8353e49cb49f5488cd3807
```
