### ISSUE TITLE
Run update.php after installation

### ISSUE THREAD

**Issue by edg2s** [MatmaRex/patchdemo#166]
In recently created wikis, abusefilter and flaggedrevs tables are not being created.

We can either wait for an upstream fix or just run update.php when creating new wikis.

**Comment by jdforrester** [comment]
Does install.php not run update.php's parts?

**Comment by MatmaRex** [comment]
It's a bug in the installer in MW core, I'll file some tasks and send some patches later today. I don't think we need to do this.

**Comment by MatmaRex** [comment]
https://phabricator.wikimedia.org/T266681

**Comment by MatmaRex** [comment]
(Three different people already responded there, so I'll let them send the patches :P)
