### ISSUE TITLE
Add a privileged user

### ISSUE THREAD

**Issue by DannyS712** [MatmaRex/patchdemo#18]
Some changes will only affect those with specific permissions; to test them, a privileged user is needed. I suggest a 'crat (has `userrights`) be created when a new test wiki is created, with a public password (can even be noted in the customized main page following #7)

**Comment by DannyS712** [comment]
...just looked through the code and found that `Patch Demo` (with the password `patchdemo`) already exists. Only suggestion is to change the password to something that doesn't result in warnings regarding it being too short, or changing the config to eliminate those

**Comment by edg2s** [comment]
We shouldn't change the config too much - people will usually want to test with default config. We could make the password more complex, but you can also just ignore the password warning.

**Comment by MatmaRex** [comment]
Right, this already exists.

The invalid password thing is indeed a bit silly, I didn't notice that until after I committed the code. Patches welcome :)

**Comment by MatmaRex** [comment]
Password fixed in https://github.com/MatmaRex/patchdemo/pull/33
