### ISSUE TITLE
patchdemobot on Phabricator should delete/update its posts when the wiki is deleted

### ISSUE THREAD

**Issue by MatmaRex** [MatmaRex/patchdemo#188]

**Comment by edg2s** [comment]
I don't know how easy it is to find and modify a post with the API. The similar gerritbot just creates a new post when a patch is abandoned so we could do that too.

Also #172 would help a little bit with this.

**Comment by edg2s** [comment]
> I don't know how easy it is to find and modify a post with the API.

I'm not sure it's even possible: https://secure.phabricator.com/conduit/method/maniphest.edit/
There is a "comment" transaction for add comments, but no "edit comment" transaction that I can see.
