### ISSUE TITLE
Warn users when they try to create a duplicate wiki 

### ISSUE THREAD

**Issue by iamjessklein** [MatmaRex/patchdemo#196]
When I'm creating a patch on testdemo I want to be warned if the wiki has already been made and given a link to the duplicate. I should still be able to make another wiki, I just want that info .... and also not to have to wait forever for the wiki to be built. 

I think this could be a simple little dialog.

**Comment by edg2s** [comment]
The slight problem is that we have to do API requests to know if the patches are duplicates (we need to know if there is a newer patchset for a given ID). We could either do the API request in the client, or put the warning on the create page as an interstitial.

We should also warn if the user is trying to create a wiki with no patches, which is much easier to detect.

**Comment by iamjessklein** [comment]
+1 @edg2s

**Comment by edg2s** [comment]
With the above patch:

> ![image](https://user-images.githubusercontent.com/180672/112489218-23ba4780-8d76-11eb-9be8-ebe7ae8714ac.png)

Clicking on the wiki link takes you to the table with the row highlighted:
> ![image](https://user-images.githubusercontent.com/180672/112489306-3af93500-8d76-11eb-9c3f-2ed432c9c609.png)
