### ISSUE TITLE
Disk full (fatal: Could not write new index file.)

### ISSUE THREAD

**Issue by urbanecm** [MatmaRex/patchdemo#199]
No patches applied, Wikimedia setup picked, says "Could not install the wiki."

Output:

```
...
+ git --git-dir=/var/www/html/repositories/mediawiki/skins/Timeless/.git worktree prune
+ git --git-dir=/var/www/html/repositories/mediawiki/skins/Timeless/.git worktree add --detach /var/www/html/wikis/17434c5c0bba1bb9acd03291bfd42288/w/skins/Timeless origin/master
Preparing worktree (detached HEAD ea7f7d8)
HEAD is now at ea7f7d8 Localisation updates from https://translatewiki.net.
+ IFS=' '
+ read -r repo dir
+ git --git-dir=/var/www/html/repositories/mediawiki/skins/Vector/.git worktree prune
+ git --git-dir=/var/www/html/repositories/mediawiki/skins/Vector/.git worktree add --detach /var/www/html/wikis/17434c5c0bba1bb9acd03291bfd42288/w/skins/Vector origin/master
Preparing worktree (detached HEAD d7f7649)
fatal: Could not write new index file.
PATCHDEMO='/var/www/html' WIKI='17434c5c0bba1bb9acd03291bfd42288' /var/www/html/deletewiki.sh 2>&1
+ rm -rf /var/www/html/wikis/17434c5c0bba1bb9acd03291bfd42288
+ mysql -u patchdemo --password=patchdemo -e 'DROP DATABASE IF EXISTS patchdemo_17434c5c0bba1bb9acd03291bfd42288'
Could not install the wiki.
```

**Comment by edg2s** [comment]
The error is just before that:
```
Preparing worktree (detached HEAD d7f7649)
fatal: Could not write new index file.
```

**Comment by MatmaRex** [comment]
Looks like that's what happens when we run out of disk space :D

```
matmarex@patchdemo:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
...
/dev/vda2        19G   18G  300M  99% /
...
```

(There's some space now because the `deletewiki.sh` cleared it.)

**Comment by MatmaRex** [comment]
I ran `deduplicate.sh` to free some more space (it usually runs as a daily cron job).

```
$ sudo ./deduplicate.sh
Now scanning "./wikis", found 4359083 files.
Now have 4359083 files in total.
Removed 4129995 files due to nonunique device and inode.
Total size is 4445585265 bytes or 4 GiB
Removed 13978 files due to unique sizes from list.215110 files left.
Now eliminating candidates based on first bytes:removed 27722 files from list.187388 files left.
Now eliminating candidates based on last bytes:removed 9016 files from list.178372 files left.
Now eliminating candidates based on sha1 checksum:removed 4700 files from list.173672 files left.
It seems like you have 173672 files that are not unique
Totally, 2 GiB can be reduced.
Now making hard links.
Failed to make hardlink ./wikis/aed6d63dcecc14ee69aa3c7405c32c4c/w/extensions/DiscussionTools/includes/ThreadItem.php to ./wikis/99e6286e6ea20f7f21525dd0f6dd66af/w/extensions/DiscussionTools/includes/ThreadItem.php
Making 146669 links.
```

I think the job still works, there were just unusually many new wikis created today.

(The "Failed to make hardlink" is apparently because that wikis was deleted as the script was running.)

**Comment by urbanecm** [comment]
Thanks! According to https://openstack-browser.toolforge.org/project/visualeditor, the patchdemo server should have 40 GB available. By default, only 20 GB is assigned to the root volume. You can easily assign the rest to /srv by following https://wikitech.wikimedia.org/wiki/Help:Adding_Disk_Space_to_Cloud_VPS_instances#Storage_quota_on_Cloud_VPS_instances.

**Comment by MatmaRex** [comment]
@urbanecm Thanks… But it looks like that way requires a new volume to be created, which means our code would then have to decide between the two places when creating a new wiki, and it would also probably make the deduplication using hardlinks only available within one volume. (Alternatively, we could move everything to the new volume, but that doesn't help if it isn't larger than the current one.)

There is an guide for an alternative approach at [Help:Resize_root_partition_of_an_OpenStack_hosted_virtual_machine](https://wikitech.wikimedia.org/wiki/Help:Resize_root_partition_of_an_OpenStack_hosted_virtual_machine) but it begins with "Do not attempt this".

Maybe the entire thing should just be moved to a more powerful instance. That might also help with poor performance that we've noticed on the demo wikis.

Meanwhile, it looks like Ed has deleted a bunch of old wikis. Maybe we should just be deleting them automatically.

**Comment by MatmaRex** [comment]
This also inspired me to check the size of the wikis' databases (rather than just the source code files), in case we did something silly like cache a copy of localisation data there.

I did this: <https://stackoverflow.com/questions/1733507/how-to-get-size-of-mysql-database> and learned that:

* most of them are tiny and reasonable (<10 MB)
* there's a few slightly larger ones (<50 MB) where we actually imported a bunch of large pages
* a single wiki has 400 MB of spam on it; see #202 about that

**Comment by urbanecm** [comment]
> @urbanecm Thanks… But it looks like that way requires a new volume to be created, which means our code would then have to decide between the two places when creating a new wiki, and it would also probably make the deduplication using hardlinks only available within one volume. (Alternatively, we could move everything to the new volume, but that doesn't help if it isn't larger than the current one.)

Right, didn't realize that.

> There is an guide for an alternative approach at [Help:Resize_root_partition_of_an_OpenStack_hosted_virtual_machine](https://wikitech.wikimedia.org/wiki/Help:Resize_root_partition_of_an_OpenStack_hosted_virtual_machine) but it begins with "Do not attempt this".
> 
> Maybe the entire thing should just be moved to a more powerful instance. That might also help with poor performance that we've noticed on the demo wikis.

+1, that would work perfectly. Would still require moving the wikis to the new volume. While moving to a new more powerful instance, i would recommend to request a dedicated project for patchdemo. It's in the visualeditor one now, and while that's probably fine (it works :)), it doesn't allow more people to maintain it. I would be happy to help you with this useful tool :)).

> Meanwhile, it looks like Ed has deleted a bunch of old wikis. Maybe we should just be deleting them automatically.

**Comment by edg2s** [comment]
Filed #233 to follow up.
