### ISSUE TITLE
Prevent spam

### ISSUE THREAD

**Issue by MatmaRex** [MatmaRex/patchdemo#202]
Disaster has struck. Who could have expected this?????

https://patchdemo.wmflabs.org/wikis/760d0aca2d743bb87426b5be2a3d15c7/w/index.php/Special:RecentChanges

(I only noticed because I checked the database sizes due to #199, and it turns out that wiki has 400 MB of spam on it already.)

For now, I disabled editing on that wiki. I'll set up something with ConfirmEdit.

**Comment by urbanecm** [comment]
Disable signing-up. If people need more accounts, they can login via the patchdemo's main acc, and go from there, so no functionality lost.

**Comment by MatmaRex** [comment]
You can edit the wikis without logging in, so I don't think disabling signups would help (although the bots I've seen apparently prefer signing up, so maybe you have a point).

The CAPTCHA I proposed is also on signups, so that should do it.

**Comment by edg2s** [comment]
That wiki is mine, I'll delete it. Screenshot for history:

![image](https://user-images.githubusercontent.com/180672/105506948-86358f80-5cc2-11eb-84e4-ee588d4e911c.png)

**Comment by edg2s** [comment]
We could also better monitor the wikis by listing the # of edits on the index page.

**Comment by edg2s** [comment]
e.g. using
```
$ php showSiteStats.php 
Total edits       : 4878
Number of articles:  100
Total pages       : 1235
Number of users   :   23
Active users      :    0
Number of images  :   44
```
