### ISSUE TITLE
Enable CentralAuth

### ISSUE THREAD

**Issue by MarcoAurelioWM** [MatmaRex/patchdemo#208]
Hello.

Would it be possible to have MediaWiki extension CentralAuth available for PatchDemo in order to test patches against its code?

Note: it should also include config for GlobalRename, GlobalRenameRequest and GlobalRenameQueue.

Thank you.

**Comment by edg2s** [comment]
If you can provide a config that gets the extension working as far you as need it, and doesn't affect the behaviour of the wiki in a way that makes it less-production like, then we can go from there.

**Comment by MarcoAurelioWM** [comment]
Hello. Thank you for your reply, and apologies for the delay in mine.
I am still interested in this issue but currently I don't have much
free time. If that is not a problem, I can try coding it, but it won't
be immediate. If that is an issue, I have no objections on this one
being closed for now. Best regards.

**Comment by MarcoAurelioWM** [comment]
Per above. No time to do this, sorry. CentralAuth is very complex.
