### ISSUE TITLE
Require to change the initial admin password

### ISSUE THREAD

**Issue by amire80** [MatmaRex/patchdemo#212]
If I understand correctly, Patch demo creates wikis with the same initial admin username and password. It's probably a good idea to require to change it after the first log in.

**Comment by edg2s** [comment]
Wikis created are not supposed to be stable, secure or long-lived. They are for short-term testing of patches only.

Often testing involves logging in or having admin access, so each wiki having a different password would make that more difficult.

**Comment by edg2s** [comment]
See also #202 and #206
