### ISSUE TITLE
When changing the password on a Patch wiki site, Firefox says that the connection is not secure

### ISSUE THREAD

**Issue by amire80** [MatmaRex/patchdemo#213]
I tried to change the password through preferences. It went to Special:ChangeCredentials. Firefox says that the connection is not secure, even though the URL is https.

**Comment by edg2s** [comment]
This could be related to #183

**Comment by edg2s** [comment]
As well as the input box warning, I also see this when posting:
![image](https://user-images.githubusercontent.com/180672/106318734-40e80380-6268-11eb-8321-b50addf7fc80.png)

**Comment by MatmaRex** [comment]
The form at Special:ChangeCredentials actually points to HTTP: `<form action="http://patchdemo.wmflabs.org/wikis/8593b7f469ef5349d6a47359e1d3b977/w/index.php?title=Special:ChangeCredentials/MediaWiki%5CAuth%5CPasswordAuthenticationRequest&amp;returnto=Special%3APreferences" method="post" enctype="application/x-www-form-urlencoded" class="mw-htmlform mw-htmlform-ooui oo-ui-layout oo-ui-formLayout">`

**Comment by MatmaRex** [comment]
It looks like we create wikis with `$wgServer` defined with either the HTTP or HTTPS protocol depending on whether you were using HTTP or HTTPS when creating the wiki. It should probably be set to protocol-relative.

**Comment by MatmaRex** [comment]
Actually… it's always HTTP. We should have been checking `$_SERVER['HTTP_X_FORWARDED_PROTO']` in addition to `$_SERVER['HTTPS']`, probably (guessing from MW code in WebRequest::detectProtocol())?

**Comment by MatmaRex** [comment]
This doesn't fix existing wikis, but any newly created ones should no longer show that error.
