### ISSUE TITLE
Add more storage capacity to the server

### ISSUE THREAD

**Issue by edg2s** [MatmaRex/patchdemo#233]
To avoid running out of disk space, like in #199 (see discussion there for config suggestions).

**Comment by MatmaRex** [comment]
I'm setting up a new, larger instance.

**Comment by MatmaRex** [comment]
Done:
- Set up a new instance patchdemo2.visualeditor.eqiad1.wikimedia.cloud (160 GB). Note: it seems that the hostname for new instances is different: unlike the old one, this can't be accessed as ~~patchdemo2.visualeditor.eqiad.wmflabs~~. I spent a lot of time figuring this out.
- Made it accessible at https://patchdemo2.wmflabs.org/ for the moment
- SSH'd in and set up the Patchdemo application
- Added disk space per https://wikitech.wikimedia.org/wiki/Help:Adding_Disk_Space_to_Cloud_VPS_instances#Adding_space_as_a_second_volume
- `df -h` shows the new volume
- Symlinked the `wikis` folder to point to the new volume:
    ```
    $ sudo mkdir /srv/patchdemo-wikis
    $ sudo chown www-data:www-data /srv/patchdemo-wikis
    $ sudo ln -s /srv/patchdemo-wikis/ wikis
    ```
- Tested that wiki creation and the deduplicate script work well

Next steps:
- Copy the wiki files and the databases (if you know how to do this, please go ahead, I'm planning to figure it out but I'm not particularly looking forward to it)
- Change DNS to point https://patchdemo.wmflabs.org/ to the new instance
- Copy the OAuth and related settings

**Comment by edg2s** [comment]
I can do the databases. The files can be done with scp?

**Comment by MatmaRex** [comment]
> The files can be done with scp?

Definitely, just have to make them talk to each other (or transfer 40 GB of data through your laptop I guess, I tried that but it seemed to be taking forever).

**Comment by MatmaRex** [comment]
I'm copying the files. I allowed matmarex@patchdemo to log in as matmarex@patchdemo2 via SSH (ran `ssh-keygen` on patchdemo, copypasted id_rsa.pub into `~/.ssh/authorized_keys` on patchdemo2).

I had to uncomment the line `AuthorizedKeysFile      %h/.ssh/authorized_keys` in `/etc/ssh/sshd_config` on patchdemo2, and then `sudo service ssh restart`. I don't really understand why it was commented out, maybe I'm breaking something Puppet-related by doing this. Oh well.

**Comment by MatmaRex** [comment]
I'm done copying the files:
```
matmarex@patchdemo:~$ time scp -q -p -r /var/www/html/wikis matmarex@patchdemo2:/var/www/html/
real    140m5.041s
user    1m53.676s
sys     6m26.226s
```
It also printed a few errors like this:
```
/var/www/html/wikis/ac4c720b7450d0f0e1703a5576e61e23/w/vendor/pear/net_smtp/README.rst: No such file or directory
```
It might be a broken symlink, and doesn't seem important.

**Comment by edg2s** [comment]
DB migration steps:
```
sudo mysqldump --all-databases > alldb.sql
```
Then `scp` this file over to the new server.
By default all tables are dropped and recreated. To preserve the wikis that had been created on the new server, I edited `alldb.sql` to remove the table drop/creation statements for the `patchdemo` database.

To import:
```
mysql < alldb.sql
```

**Comment by MatmaRex** [comment]
And to finish this:
* Updated the DNS in Horizon to point to the new server
* Copied config.php from the old server
* Added this to .htaccess to disable the site on the old server:
    ```
    Deny from all
    ErrorDocument 403 "Migrating to a new server. If you can see this, your DNS data is out of date."
    ```

https://patchdemo.wmflabs.org/ is the new server for me now.

**Comment by MatmaRex** [comment]
One last note: I had to fix the ownership of the wikis' files after copying them, to make the deduplicate script to work again:
```
sudo chown -R www-data:www-data wikis/*
```
