### ISSUE TITLE
Incorrect alignment of the warning

### ISSUE THREAD

**Issue by kizule** [MatmaRex/patchdemo#276]
When you have created a wiki without specifying the patch or a wiki is created with the merged patch(es), there is a warning.

There isn't an empty line before warning and after checkbox for "Previously generated wikis".

See:
![image](https://user-images.githubusercontent.com/28963303/110872659-84567880-82d0-11eb-9538-9f06a1f1771a.png)

I have a fix for this:
![image](https://user-images.githubusercontent.com/28963303/110872691-946e5800-82d0-11eb-9889-e84ec15b5987.png)

**Comment by edg2s** [comment]
Fixed by #283

**Comment by kizule** [comment]
Looks great, thank you very much for working on this!
