### ISSUE TITLE
Can't recreate a wiki

### ISSUE THREAD

**Issue by nardog** [MatmaRex/patchdemo#282]
I'm having a trouble recreating a demo for [674164](https://gerrit.wikimedia.org/r/c/mediawiki/extensions/CodeEditor/+/674164). It stops at "+ mysql -u patchdemo --password=patchdemo -e 'DROP DATABASE IF EXISTS patchdemo_698cb3b62d'" and says "Could not install wiki."

I deleted the first demo for the patch because it was throwing some PHP errors for some reason (I changed the password for the admin account for security, was that it?). Is recreation not an option, or is there some other reason I can't recreate it?

**Comment by edg2s** [comment]
There should be no restriction to recreating wikis, or creating multiple wikis with the same patches. I managed to create a wiki with that patch.
