### ISSUE TITLE
Translate extension in patchdemo

### ISSUE THREAD

**Issue by ihurbainpalatin** [MatmaRex/patchdemo#320]
May I please have an option to have the Translate extension in patchdemo? Thanks!

**Comment by edg2s** [comment]
Does you need any extra config in LocalSettings.php?

**Comment by ihurbainpalatin** [comment]
It needs to be loaded, and ideally to have some permissions for some users, as per https://www.mediawiki.org/wiki/Help:Extension:Translate/Configuration. 
I actually don't need that for my own needs right now (because I only need the rendering part, not the translate administration/review/actual translation parts), but if someone else needs it they may appreciate a functional install.
