### ISSUE TITLE
install.php fails on REL1_30

### ISSUE THREAD

**Issue by edg2s** [MatmaRex/patchdemo#374]
```
+ php /var/www/html/wikis/a29030677b/w/maintenance/install.php --dbname=patchdemo_a29030677b --dbuser=patchdemo --dbpass=patchdemo --confpath=/var/www/html/wikis/a29030677b/w --server=https://patchdemo.wmflabs.org --scriptpath=/wikis/a29030677b/w --with-extensions --pass=patchdemo1 'Patch demo (REL1_30)' 'Patch Demo'
This script must be run from the command line
```

**Comment by jdforrester** [comment]
Why are you trying to install REL1_30? It's not been supported for years.

**Comment by edg2s** [comment]
In theory regression testing. We should either fix these installs or remove them from the dropdown.

**Comment by jdforrester** [comment]
1.30.x went EOL in June 2019. I'd recommend dropping it.

**Comment by MatmaRex** [comment]
By the way, the MW 1.30 bug was fixed by https://github.com/wikimedia/mediawiki/commit/659f3779c33748ac66fb307e639648d839580130.

**Comment by MatmaRex** [comment]
(Apparently you need to uncheck the TimedMediaHandler and QuickSurveys extensions, because they fail horribly.)

**Comment by edg2s** [comment]
> (Apparently you need to uncheck the TimedMediaHandler and QuickSurveys extensions, because they fail horribly.)

For reference, TimedMediaHandler required the MwEmbedSupport extension in REL1_30, which no longer exists and so we don't list it. QuickSurveys worked for me, at least locally...
