### ISSUE TITLE
Can't create wiki with WikiLambda

### ISSUE THREAD

**Issue by edg2s** [MatmaRex/patchdemo#385]
```
PHP Warning:  file_get_contents(/srv/patchdemo-wikis/5898464cf3/w/extensions/WikiLambda/function-schemata/data/definitions/dependencies.json): failed to open stream: No such file or directory in /srv/patchdemo-wikis/5898464cf3/w/extensions/WikiLambda/includes/Hooks.php on line 243
RuntimeException from line 245 of /srv/patchdemo-wikis/5898464cf3/w/extensions/WikiLambda/includes/Hooks.php: Could not load dependencies file from function-schemata sub-repository of the WikiLambda extension. Have you initiated & fetched it? Try `git submodule update --init --recursive`.
```

We run submodule update for VE so that probably needs to be done here too:

https://github.com/MatmaRex/patchdemo/blob/52424fa52e7414e2f408bb03bb814625d267f046/new/checkout.sh#L25-L28

**Comment by edg2s** [comment]
@jdforrester

**Comment by edg2s** [comment]
After adding the `submodule update` I get an error from `maintenance/edit.php`:
```
You do not have permission to edit this page, for the following reason:
The provided title 'Main_Page' is not valid for a ZObject.
```

cc @jdforrester again

**Comment by jdforrester** [comment]
Have you run install.php (which creates a page in NS0 called Main Page) before you install the extension? Yeah, that'll break the world. Don't do that, please?

**Comment by edg2s** [comment]
The installer runs after **all** the repos have been checked out.

**Comment by edg2s** [comment]
#393 sidesteps this issue, but you end up with a wiki where the main page is uneditable

**Comment by jdforrester** [comment]
Yeah, there's no programmatic way for our extension to say "don't put the Main Page in the main namespace please", AFAICT.

**Comment by edg2s** [comment]
Are you not supposed to have a Main Page? What is the desired setup?

**Comment by jdforrester** [comment]
The Main Page should be at [[Project:Main Page]], like with Wikibase.

**Comment by MatmaRex** [comment]
There are some hooks that let you override localisation messages, maybe we could use them to override 'mainpage'. Not sure if that belongs in WikiLambda though…

Alternatively, we could use maintenance/edit.php to edit MediaWiki:Mainpage to be "Project:Main Page" if WikiLambda extension is enabled.

Not sure in which order it all occurs though, or how it interacts with the installer…

**Comment by edg2s** [comment]
> The Main Page should be at [[Project:Main Page]], like with Wikibase.

And how are you doing this during a normal setup? Clearly the installer knows nothing about this at the moment:

https://patchdemo.wmflabs.org/wikis/6edd61eea0/wiki/Main_Page

**Comment by jdforrester** [comment]
> > The Main Page should be at [[Project:Main Page]], like with Wikibase.
> 
> And how are you doing this during a normal setup? Clearly the installer knows nothing about this at the moment:
> 
> https://patchdemo.wmflabs.org/wikis/6edd61eea0/wiki/Main_Page

Manually, changing [[MediaWiki:Mainpage]] to be "Project:Main Page", the same way that WikibaseRepo wikis have to be tweaked on creation. But PatchDemo doesn't support WikibaseRepo yet, so I guess this is the first you've encountered the issue?

**Comment by edg2s** [comment]
The above patch imports MediaWiki:Mainpage as "Project:Main Page" (always English, but I assume this isn't a problem for WF wikis). There is still a 0:Main_Page created by the installer which would need to be deleted manually.

**Comment by jdforrester** [comment]
If you can somehow specify the `mainpage` message early on, then the installer will follow it when creating the main page (as it uses `Title::newMainPage()`). But AFAICT there's no way to set the `mainpage` message in the options passed to the installer? Should I file a Phab task?

**Comment by jdforrester** [comment]
Filed as https://phabricator.wikimedia.org/T297434
