### ISSUE TITLE
Add translate-manage right to admins

### ISSUE THREAD

**Issue by tacsipacsi** [MatmaRex/patchdemo#404]
Please add the `translate-manage` right to admins in [extensions-Translate.php](https://github.com/MatmaRex/patchdemo/blob/master/localsettings/extensions-Translate.php). I debugged on [51f093b25e](https://patchdemo.wmflabs.org/wikis/51f093b25e/wiki/Main_Page) quite a bit until I found out why I can’t see the new aggregate group form on Special:AggregateGroups… I can’t think of any negative effect of it except for making testing very orthopedic situations harder/impossible, but Patch Demo should aim at providing a usual environment, and this right is in the [default right set for translation admins on Wikimedia](https://phabricator.wikimedia.org/source/mediawiki-config/browse/master/wmf-config/CommonSettings.php;21ebb15b8a00$2955).

**Comment by tacsipacsi** [comment]
404 new aggregate group form not found. :)

**Comment by edg2s** [comment]
I think you just need to add something like this

https://github.com/MatmaRex/patchdemo/blob/master/new/postinstall.sh#L35-L37

**Comment by tacsipacsi** [comment]
Not even assigning an extra group needed, it’s enough to add `$wgGroupPermissions['sysop']['translate-manage'] = true` to the extension-specific PHP file I linked above. SecurePoll seems to [query whether a user is part of the hardcoded `electionadmin` group](https://phabricator.wikimedia.org/diffusion/ESPO/browse/master/?grep=%27electionadmin%27) instead of using a user right. Translate doesn’t do such silly things—in fact, `translationadmin` membership is not only not queried by the extension, [this string isn’t even present in the codebase](https://phabricator.wikimedia.org/diffusion/EFLR/browse/master/?grep=translationadmin), it’s just a Wikimedia thing (for example, [translatewiki.net](https://translatewiki.net/w/api.php?action=query&meta=siteinfo&siprop=usergroups) has a `transadmin` group instead, with a different right set). So adding this group using the shell script wouldn’t make a difference (except for that maybe it causes an exception when one tries to add a nonexistent group?).

**Comment by edg2s** [comment]
If you submit a PR we can merge it
