### ISSUE TITLE
Enable wikidiff2 on patch demo instances

### ISSUE THREAD

**Issue by jdlrobson** [MatmaRex/patchdemo#414]
We use [wikidiff2](https://www.mediawiki.org/wiki/Wikidiff2) in production

Without it, MobileFrontend displays a diff page very different from the one it shows in production making it hard to QA changes to the diff page e.g. https://phabricator.wikimedia.org/T171726. Could this be enabled on the patchdemo instances?

Example: https://patchdemo.wmflabs.org/wikis/3596c71251/w/index.php?title=Special:MobileDiff/32&type=revision&mobileaction=toggle_view_mobile

**Comment by edg2s** [comment]
Installed.

**Comment by edg2s** [comment]
I installed the Debian package version, but there have been some recent changes to the library to enable copy/paste of diffs that are not included. This would require us to install it from source, which seems like a bit of a hassle to maintain.
