### ISSUE TITLE
Old demo's timestamp updated when a new demo is created

### ISSUE THREAD

**Issue by DemianX0** [MatmaRex/patchdemo#42]
I've created this demo:  0516ae808872d38b5bdf96e2559feeb1  patch:  578568,10
And another demo was created additionally:  24b6fd1f6a50fc53846f92f943ce79a4   patches:  578995,11, 579572,2
16 seconds later.

I haven't copied in the change ids "578995,11, 579572,2" this time, but I think (not sure tho) I have made a demo of those ca. 2 weeks ago, then deleted it. It's very likely that I've copied those change ids into the textarea at one point.

This happened the second time now, first time 2 days before. I don't remember if the patches were the same, I've deleted the demo very quickly.

Are these stuck somewhere in a queue?

I've created another demo:  16d4afb6c4012cac810121fdbbfce904
and it has a twin too:  4cb27da34f62e845d77be74526fb149c
different change ids...

This is spooky...

**Comment by DemianX0** [comment]
Yet another twin comes out of the cloning machine. I've created patches from these change ids before and deleted them already.

**Comment by DemianX0** [comment]
Well... it's possible those weren't duplicates, but my older patches, that somehow got the timestamp updated...  Too bad I've deleted those 😂

**Comment by MatmaRex** [comment]
I've noticed the timestamps changing too. I think it's a side-effect of deduplication.

**Comment by edg2s** [comment]
Could be #46

**Comment by DemianX0** [comment]
> I've noticed the timestamps changing too. I think it's a side-effect of deduplication.

Interesting... the timestamps with a few second - one minute difference would fit that theory.
The timestamp is the last modified date of some file? Which one?

**Comment by edg2s** [comment]
The wiki directory (wiki/<hash>)

**Comment by edg2s** [comment]
I too have noticed some strange timestamp touching:

![image](https://user-images.githubusercontent.com/180672/79881703-78787400-83e9-11ea-97f1-e6ed9baf87e5.png)

"577601,8: WIP Tabs" was created several weeks ago, but when I pulled a new version of it ("577601,18: WIP Switching between VE & wikitext (plain)") it got given the same timestamp bumping it to the top of the table.

The 3rd row in that table also got given a newer timestamp when the 4th row was added.

**Comment by DemianX0** [comment]
> > I've noticed the timestamps changing too. I think it's a side-effect of deduplication.

> The wiki directory (wiki/), which will change if any file inside is modified.

Is it possible that deduplication changes the inode number of a file entry **in the old wiki** folder, thus also touching the folder's timestamp?

**Comment by MatmaRex** [comment]
Probably.

I think we should store the creation timestamp explicitly in some file, rather than rely on the filesystem metadata. (Similar to `creator.txt`; maybe they should be together in some `.json` file.)

**Comment by edg2s** [comment]
I think just reading the timestamp from a file rather than a folder would help.

**Comment by edg2s** [comment]
I tested #48 on the server, using the mtime of LocalSettings.php to back-fill and it appears to be in a more sensible order now. Going forward a timestamp will be stored in a file so we don't have to rely on the file system.

**Comment by DemianX0** [comment]
That's great, thank you!

**Comment by DemianX0** [comment]
I've just created a demo and this was the result... 

[![Screenshot from Gyazo](https://gyazo.com/444416d421610e50bb9d0fb99ce46274/raw)](https://gyazo.com/444416d421610e50bb9d0fb99ce46274)

**Comment by MatmaRex** [comment]
Fascinating.

I'm not sure how that happened, but it looks like something caused all the timestamps to be read as `0`, which was the interpreted as the current date, and then cached. It might have been a buggy old version of Ed's code, or caused by deploying and then reverting the change? Anyway, I cleared the cache (`wikicache.json`), updated the code, and it looks fine now.

**Comment by DemianX0** [comment]
Although bit confusing, it was funny :smiley: 
All timestamps seem to be back to normal now. Thank you!
