### ISSUE TITLE
Expose OOUI demo page when building OOUI patches

### ISSUE THREAD

**Issue by edg2s** [MatmaRex/patchdemo#432]
These are already available at a public URL, e.g. https://patchdemo.wmflabs.org/wikis/028e22ab6e/w/build/ooui/demos

We should add a link to Main_Page when OOUI patches are present.

**Comment by catrope** [comment]
We already have a different deployment preview setup through Netlify that (slightly) predates this implementation, and that publishes the demo site automatically when a new patch is uploaded: https://777823--wikimedia-codex.netlify.app/components/text-input.html

But it would be easy to add this functionality to PatchDemo too, which would help people easily find the demos and docs for the Codex version that's deployed to a given PatchDemo wiki, and would allow the demo to be viewed for outdated patchsets (as you can probably infer from the URL pattern, our Netlify setup overwrites the deployment preview when a new patchset is uploaded).

**Comment by catrope** [comment]
Looks like it's technically already there, it's just at a not very useful URL and it's broken because the right URL prefix isn't passed to the build: https://patchdemo.wmflabs.org/wikis/d35c65739c/w/build/codex/packages/codex-docs/docs/.vitepress/dist/ . I'll take a stab at fixing that.

**Comment by edg2s** [comment]
I ran `npm run doc` manually and got to that URL. I don't know if the docs are built by just build-all.

**Comment by catrope** [comment]
They are. `npm run build-all` runs a superset of the commands that `npm run doc` runs.
