### ISSUE TITLE
Add IPInfo

### ISSUE THREAD

**Issue by MarcoAurelioWM** [MatmaRex/patchdemo#467]
[IPInfo](https://www.mediawiki.org/wiki/Extension:IPInfo) is in WMF Production wikis for the IP Masking project/experiment. To allow developers to easily test interface changes, I'd like to have it on patchdemo. I am however not sure how to configure https://www.mediawiki.org/wiki/Extension:IPInfo#Free_test_data though.

**Comment by MatmaRex** [comment]
> I am however not sure how to configure https://www.mediawiki.org/wiki/Extension:IPInfo#Free_test_data though.

I guess you could make the installation script download them? This would be implemented around here: https://github.com/MatmaRex/patchdemo/blob/master/new/postinstall.sh#L63

Looks like they kind of support doing that: https://dev.maxmind.com/geoip/updating-databases?lang=en#directly-downloading-databases but there's some stuff about license keys, I'm not sure if it'd be okay to just add it publicly to this repo. (It's okay from my side, as long as I'm not the one who has to register there to get it, I just don't know if MaxMind terms of use allow that.)
