### ISSUE TITLE
Please enable syntax highlighting (CodeMirror) for WikiTextEditor 2010 and 2017

### ISSUE THREAD

**Issue by DemianX0** [MatmaRex/patchdemo#47]
https://www.mediawiki.org/wiki/Extension:CodeMirror

On live servers, there is a stylus button on the toolbar just left from "Advanced" in WTE2010:
https://www.mediawiki.org/w/index.php?title=2017_wikitext_editor&action=edit&useskin=timeless
to turn on syntax highlighting. It's missing here:
http://patchdemo.wmflabs.org/wikis/8aa1bf729181edce0a4d14d78d04ee3f/w/?useskin=timeless&action=edit

The button is in the hamburger menu dropdown in WTE2017 (VisualEditor's new wikitext editor).
Missing:
http://patchdemo.wmflabs.org/wikis/1e7905405c7e9513605490187cb54a43/w/?useskin=timeless&veaction=editsource

**Comment by edg2s** [comment]
Fixed

**Comment by DemianX0** [comment]
I've created a new demo, but there's no "Syntax highlighting" option either in WTE2010 or WTE2017:
http://patchdemo.wmflabs.org/wikis/0f7a0255cd311c74cf42738402c6f8b9/w/index.php?title=Main_Page&action=edit

There's no "CodeMirror" in the creation log.
I assumed this is live... It seems I have no idea how and when deployments are done.

**Comment by MatmaRex** [comment]
It wasn't fixed, we didn't merge that commit into master :D

**Comment by DemianX0** [comment]
Works now, big thanks!
