### ISSUE TITLE
Add Phonos extension

### ISSUE THREAD

**Issue by MusikAnimal** [MatmaRex/patchdemo#480]
This is an upcoming extension from Community Tech to be deployed on WMF.

The tricky part is we're currently planning to use the Google engine (`$wgPhonosEngine`), which needs a private API key. Does Patch Demo have something like a PrivateSettings.php? I can share the API key over email or Slack (which won't be the same key we will use for production, but it still needs to be private). If keeping the key out of version control is not possible, there's no need to add Phonos to Patch Demo at this time as we will use a test wiki on VPS instead.

Docs: https://www.mediawiki.org/wiki/Extension:Phonos

**Comment by edg2s** [comment]
We currently have [config.php](https://github.com/MatmaRex/patchdemo/blob/master/config.default.php) that stores keys for Patch Demo itself. We don't currently have any PrivateSettings.php infrastructure, but it probably wouldn't be that hard to setup.

One shouldn't consider the Patch Demo environment that secure, so if we did do something you would probably have to have a plan if the key leaked.

Thoughts @MatmaRex?

**Comment by edg2s** [comment]
Also which part of the extension would you be testing? Without the Google engine you can still test the UI, and presumably you have other environments for testing the actual sound output?

**Comment by MatmaRex** [comment]
The Patch Demo environment is definitely not secure.

I'd prefer just setting up the extension with the parts depending on the API disabled (similar to e.g. Score, which has some complicated dependencies that we just disabled: https://github.com/MatmaRex/patchdemo/blob/master/localsettings/extensions-Score.php), or pointed to a public API endpoint of Wikimedia wikis (similar to e.g. Citoid: https://github.com/MatmaRex/patchdemo/blob/master/localsettings/extensions-Citoid.php).

**Comment by MusikAnimal** [comment]
> One shouldn't consider the Patch Demo environment that secure, so if we did do something you would probably have to have a plan if the key leaked.

Yes, we can make a separate key just for Patch Demo, and we can also limit it to referrers under patchdemo.wmflabs.org, as well as the WMCS IP range. We get something like 5 million free requests so I think this should suffice for the lifetime of us testing on Patch Demo.

> Also which part of the extension would you be testing? Without the Google engine you can still test the UI, and presumably you have other environments for testing the actual sound output?

If Patch Demo doesn't work out we can make a test wiki on VPS (which we might do regardless). This is more for the designers and product. Our engineers including QA has a local environment they can use for testing. That said, I suppose being able to test the UI by itself is still helpful, so I take back my comment that Patch Demo isn't useful if we can't use Google :) And actually, as of today, we have expanded the scope of functionality so there are other things to test, too.

> I'd prefer just setting up the extension with the parts depending on the API disabled

Alright! Unless any of what I said above doesn't work, let's just add Phonos with `$wgPhonosEngine` set to `larynx`. This should work out of the box.

Thank you!

**Comment by edg2s** [comment]
Tested here: https://patchdemo.wmflabs.org/wikis/3eea623576/wiki/Phonos (some IPAs work, some return 500 errors)
