### ISSUE TITLE
Progress bar on new.php overlaps header when scrolling down

### ISSUE THREAD

**Issue by MatmaRex** [MatmaRex/patchdemo#484]
Progress bar on new.php overlaps header when scrolling down:

![image](https://user-images.githubusercontent.com/160413/182453211-a99ad4ee-0696-46c2-8a94-5569bda2757f.png)

Probably caused by last OOUI update?

**Comment by edg2s** [comment]
Fixed upstream: https://gerrit.wikimedia.org/r/c/oojs/ui/+/820130

**Comment by edg2s** [comment]
Fixed by one of our OOUI updates:
![image](https://github.com/MatmaRex/patchdemo/assets/180672/004e882a-e24f-4c40-924c-196a806c405f)
