### ISSUE TITLE
Please add MediaSearch

### ISSUE THREAD

**Issue by josephseddon** [MatmaRex/patchdemo#487]
It would be great if we could add MediaSearch to this tool.

**Comment by edg2s** [comment]
This extension has a hard dependency on CirrusSearch and ElasticSearch, which requires setting up an elasticsearch server. We don't have any non-PHP services on Patch Demo (https://github.com/MatmaRex/patchdemo#limitations).

I note it is possible to configure the extension with an external search API (https://www.mediawiki.org/wiki/Extension:MediaSearch#Configuration), but the extension would need to remove the hard dependencies for us to be able to deploy it.

**Comment by edg2s** [comment]
See https://phabricator.wikimedia.org/T314713

**Comment by edg2s** [comment]
Parent task is resolved. The feature still doesn't really work without those dependencies, but the wiki installs which is good enough for me.
