### ISSUE TITLE
Allow installation of patchdemo in a sub folder

### ISSUE THREAD

**Issue by edg2s** [MatmaRex/patchdemo#5]
Currently it is assumed that you are installing in `/var/www` on an otherwise empty VM. You may want to install in `/var/www/patchdemo`, e.g. for local developement.

**Comment by MatmaRex** [comment]
Well, that's what I wrote in the readme, but you could probably put it elsewhere, and do some Apache magic to serve it from the root of whatever domain you put it on. I'm not sure if I want to have more path handling here.

**Comment by edg2s** [comment]
> do some Apache magic to serve it from the root of whatever domain you put it on

Not without breaking all the other sites I have running.

> I'm not sure if I want to have more path handling here.

It would only need the path to be changed in three places, once in createwiki.sh where scriptpath is set, and twice in the HTML in new.php.

**Comment by MatmaRex** [comment]
> > do some Apache magic to serve it from the root of whatever domain you put it on
> 
> Not without breaking all the other sites I have running.

Sorry, I was thinking that you'd put it on a different domain than http://localhost/, e.g. http://patchdemo.localhost/ or http://localhost:1234/. I'm pretty sure this is possible.
