### ISSUE TITLE
New wikis can't be created since MediaWiki requires PHP 7.4

### ISSUE THREAD

**Issue by MatmaRex** [MatmaRex/patchdemo#500]
New wikis can't be created since MediaWiki requires PHP 7.4, and https://patchdemo.wmflabs.org/ runs on debian-10.0-buster which has PHP 7.3.

**Comment by jdforrester** [comment]
Sorry. :-(

**Comment by MatmaRex** [comment]
I solved this for now by installing the 7.4 packages from https://deb.sury.org/.

1. Following the instructions from https://packages.sury.org/php/README.txt
1. `sudo apt-get install php7.4 php7.4-mysql php7.4-intl php7.4-xml php7.4-mbstring php7.4-curl`
2. `sudo service apache2 restart`

I didn't update the code in `setup.sh`, since we won't need this after migrating to debian-11.0-bullseye.

Unfortunately, this is not all… #501

**Comment by MatmaRex** [comment]
Wikis can be created now, but they can't run: https://patchdemo.wmflabs.org/wikis/b4d5e22fda/w/
`Fatal error: Uncaught ExtensionDependencyError: Parsoid is not compatible with the current PHP version 7.3.31), it requires: >= 7.4.`

**Comment by MatmaRex** [comment]
Fixed by:
```
sudo a2enmod php7.4
sudo a2dismod php7.3
```

**Comment by MatmaRex** [comment]
Everything seems to work correctly now, but I'll leave this open as a reminder that we're running on a configuration that is not reflected in the source code, until we can migrate to debian-11.0-bullseye.

**Comment by MatmaRex** [comment]
Done in #516
