### ISSUE TITLE
New wikis can't be created since MediaWiki requires Composer 2

### ISSUE THREAD

**Issue by MatmaRex** [MatmaRex/patchdemo#501]
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/dbal 3.4.2 -> satisfiable by doctrine/dbal[3.4.2].
    - doctrine/dbal 3.4.2 requires composer-runtime-api ^2 -> no matching package found.
```

**Comment by MatmaRex** [comment]
I think this is an unaccounced backwards compatibility break.

**Comment by jdforrester** [comment]
We started requiring composer 2 a while ago. Possibly it was masked?

**Comment by MatmaRex** [comment]
Composer 1 has been working just fine for me locally as well, until today. I have seen no notice that the support was removed.

Looks like this will be also fixed by migrating to debian-11.0-bullseye in the long term. For now, I'm figuring out how to install a custom version.

**Comment by jdforrester** [comment]
Yeah, composer 1 was fake-allowed by master's old dbal version it appears. We didn't allow this in any released version of MW because we've used dbal 3.x since REL1_35. Consequently, not an announceable change.

**Comment by MatmaRex** [comment]
Resolved following the instructions at <https://getcomposer.org/download/>:
```
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
sudo mv composer.phar /usr/local/bin/composer
```

**Comment by MatmaRex** [comment]
Everything seems to work correctly now, but I'll leave this open as a reminder that we're running on a configuration that is not reflected in the source code, until we can migrate to debian-11.0-bullseye.

**Comment by MatmaRex** [comment]
Done in #516
