### ISSUE TITLE
Website down - Warning: mysqli::__construct(): (HY000/2002): Connection refused

### ISSUE THREAD

**Issue by NovemLinguae** [MatmaRex/patchdemo#505]
https://patchdemo.wmflabs.org/

```
Warning: mysqli::__construct(): (HY000/2002): Connection refused in /var/www/html/includes.php on line 30
Connection refused
```

**Comment by MatmaRex** [comment]
We seem to have ran out of disk space on `/`.

**Comment by MatmaRex** [comment]
I ran `apt autoclean` to free some disk space, then `service mysql restart` to bring MySQL back up. I still don't know what is using it.

**Comment by edg2s** [comment]
I know we put repos on the secondary storage (138gig), are the mysql files on `/`?

**Comment by edg2s** [comment]
There are some mysql cleanup processes that might compress that, or we could try and move it to the secondary storage?

**Comment by MatmaRex** [comment]
I'm running `mysqlcheck --optimize --all-databases` right now, which seems to be helping (slightly), but we'll probably have to think about moving it…

**Comment by MatmaRex** [comment]
Also, `/var/www/html/repositories/` is 4.1 GB, which is also bigger than I'd think reasonable.

**Comment by edg2s** [comment]
A lot of the problem is down to volume of wikis. I routinely delete old wikis, but it is time consuming and boring.

We could have a library-loan style system, where a wiki automatically expires after 3 months, unless you login and renew it for a month? The homepage could show how long wikis have, and warn when they are close to expiry.

**Comment by MatmaRex** [comment]
I would hate that. We can just get a bigger virtual machine when migrating to Bullseye.

(It's down to 5.8 GB now, but I think that's mostly because you've been deleting old wikis, rather than thanks to the optimization.)

**Comment by MatmaRex** [comment]
I also ran `git gc` on all repos: ```root@patchdemo2:/var/www/html/repositories# for d in `find . -name ".git"`; do cd $d/..; echo `pwd`:; sudo -u www-data git gc; cd -; done```

Down to 3.1 GB from 4.1 GB.

**Comment by MatmaRex** [comment]
It should keep working for a while now.

**Comment by edg2s** [comment]
> I would hate that. We can just get a bigger virtual machine when migrating to Bullseye.

Are you volunteering to delete all the old wikis :) ? But seriously, the number of users is growing, which means that the number of wikis grows quadratically. A bigger disk buys us time, but then when it comes to cleaning up the old wikis that job is just bigger and slower.
