### ISSUE TITLE
Add ContactPage to list of included repos

### ISSUE THREAD

**Issue by Dreamy-Jazz** [MatmaRex/patchdemo#511]
I want to be able to test where https://phabricator.wikimedia.org/T325267 comes from using https://gerrit.wikimedia.org/r/c/mediawiki/extensions/ContactPage/+/869331 . However, ContactPage is not listed as a repo that is loaded. Would be nice to have it as a possible extension to load. It allows sending emails using a contact form, but if the mailer is not defined then it should never send emails.

**Comment by MatmaRex** [comment]
Done. I added some default config to make it work. Please submit a pull request if you want to tweak it.

To test the emails without actually sending email, you can enable the Inbox extension, which will intercept all emails and display them within the wiki on a special page, e.g. https://patchdemo.wmflabs.org/wikis/f34425e915/wiki/Special:Inbox

**Comment by Dreamy-Jazz** [comment]
Thanks for the quick resolve!
