### ISSUE TITLE
Make Vector 2022 the default skin

### ISSUE THREAD

**Issue by edg2s** [MatmaRex/patchdemo#525]
Now that it is default on enwiki, the majority of users on WMF hosted sites will be seeing this skin, so we should update our config accordingly.

**Comment by MatmaRex** [comment]
We have no config for it, we're just using the MediaWiki default, and that is the old Vector still: https://gerrit.wikimedia.org/g/mediawiki/core/+/db9d38811664401927139b46174fb771ffcdfebb/includes/MainConfigSchema.php#5146

**Comment by edg2s** [comment]
I don't how long it will be before that gets updated, but we should update ours asap.

If we do override it, we should probably only do it for recent release builds.
