### ISSUE TITLE
Trying to a create a wiki with a branch causes **all** extensions to be cloned

### ISSUE THREAD

**Issue by edg2s** [MatmaRex/patchdemo#527]
For example, using branch 1.40wmf21, with minimal extensions, I get:
```
...
Fetching submodules...

PATCHDEMO='/var/www/html' NAME='37afae8625' /var/www/html/new/submodules.sh
+ '[' -d /var/www/html/wikis/37afae8625/w/extensions/VisualEditor ']'
+ cd /var/www/html/wikis/37afae8625/w/extensions/VisualEditor
+ git submodule update --init --recursive
Submodule 'extensions/3D' (https://gerrit.wikimedia.org/r/mediawiki/extensions/3D) registered for path '../3D'
Submodule 'extensions/ActiveAbstract' (https://gerrit.wikimedia.org/r/mediawiki/extensions/ActiveAbstract) registered for path '../ActiveAbstract'
Submodule 'extensions/AdvancedSearch' (https://gerrit.wikimedia.org/r/mediawiki/extensions/AdvancedSearch) registered for path '../AdvancedSearch'
Submodule 'extensions/AntiSpoof' (https://gerrit.wikimedia.org/r/mediawiki/extensions/AntiSpoof) registered for path '../AntiSpoof'
...
```

Note this is every extension that exists, not just those listed in all.txt here.

It then proceeds to start cloning every repo, which obviously takes for ever.

**Comment by edg2s** [comment]
Rolling back the last 200 changes in patchdemo to March 2021 as this bug is still present, so I think we can rule out a regression in our code.

**Comment by edg2s** [comment]
It also fails with old repos (e.g. REL1_35), so either:
* we have made a change to our git repo, including historic branches
* or something in the way git works has changed
?

**Comment by MatmaRex** [comment]
It might have always been like this. I think it's because the branches other than master have submodules added in extensions/ and skins/, so Git clones them as well, and then our code and MediaWiki assume that they were supposed to be there.

**Comment by edg2s** [comment]
I've created branch wikis in the past and they were relatively fast. With this bug it takes tens of minutes, so something has changed.

**Comment by edg2s** [comment]
@krinkle Has something changed in how we handle the /extensions submodules in the repo that would have cause this?

**Comment by Krinkle** [comment]
@edg2s I'm not able to think of any changes in the past three months in Gerrit config or Git CLI releases that would change how or which submodules are initialised for a MediaWiki branch.

What seems supicious to me is that the quoted bit of build output above is moving to the VE subdirectory specifically before it runs that Git command. That suggests to me that perhaps it exists there only for VE's submodules but perhaps not working correctly in this context. The fact that it is conditional suggests that VE is optional, and some patchdemo-specific code is looking for its existence and then running this command to init the VE core submodule under "lib". However, it seems for your build, this was either not a directory or not (yet) a Git directory at that point, and so it gets interpreted as a command on the core repo with CWD just happening to be in a sub directory that (to us) looks like its own repository, and thus it starts cloning extensions. Note the `../` prefix in that context.

So my guess is, either some dirty state is left behind on the server, or perhaps it is specific to whether the VE checkbox is enabled, and when it isn't enabled, I guess it sees the unitilalized extension directory from the submodule, and that makes it break.

I hope this helps in narrowing a fix from where we are today, even if it doesn't help find the temporal cause.

**Comment by edg2s** [comment]
>  I guess it sees the unitilalized extension directory from the submodule, and that makes it break.

Thanks, I've seen something like that before. We can fix the checks to look for a .git sub folder maybe...
