### ISSUE TITLE
Allow applying a previous Patch Set of a Change

### ISSUE THREAD

**Issue by DemianX0** [MatmaRex/patchdemo#53]
Accept changeset numbers in the format: `578568,12`

It so happened that I needed to test a previous PS. I had to resubmit as the last PS.
Low prio.

**Comment by edg2s** [comment]
You should be able to enter the change hash

**Comment by edg2s** [comment]
We use the Gerrit search API:
https://github.com/MatmaRex/patchdemo/blob/54f717c/new.php#L102

One would just need to detect this pattern (`[0-9]+,[0-9]+)`) and use the appropriate API to fetch the correct patch
