### ISSUE TITLE
Error posting to phabricator

### ISSUE THREAD

**Issue by kemayo** [MatmaRex/patchdemo#533]
I was creating [this wiki](https://patchdemo.wmflabs.org/wikis/56e9396b0e/wiki/Main_Page) and the build process stalled out on the "posting to phabricator" stage. I scrolled down and found this error in the log:

```Fatal error: Uncaught BuildR\Foundation\Exception\RuntimeException: Malformed JSON response! Message: Syntax error in /var/www/html/vendor/zolli/phabricator-php-api/src/Response/ConduitResponse.php:50 Stack trace: #0 /var/www/html/vendor/zolli/phabricator-php-api/src/Response/ConduitResponse.php(33): Phabricator\Response\ConduitResponse->processRawResponse() #1 /var/www/html/vendor/zolli/phabricator-php-api/src/Phabricator.php(151): Phabricator\Response\ConduitResponse->__construct() #2 /var/www/html/includes.php(505): Phabricator\Phabricator->__call() #3 /var/www/html/new.php(609): post_phab_comment() #4 {main} thrown in /var/www/html/vendor/zolli/phabricator-php-api/src/Response/ConduitResponse.php on line 50```

**Comment by kemayo** [comment]
It looks like there might have been a phabricator semi-outage going on around this time, so this could be totally transitory conditions on that end rather than anything wrong with patchdemo.

**Comment by edg2s** [comment]
I suppose this should result in a warning at the top of the page, maybe with a button to retry? (Rather than deleting the wiki)
