### ISSUE TITLE
Undefined property after login with OAuth

### ISSUE THREAD

**Issue by hashar** [MatmaRex/patchdemo#535]
After successfully login in to https://patchdemo.wmflabs.org/ I am shown the list of previously generated wikis and at the top of the page I see:
```counterexample
Notice: Undefined property: stdClass::$key in /var/www/html/vendor/mediawiki/oauthclient/src/Client.php on line 181

Notice: Undefined property: stdClass::$secret in /var/www/html/vendor/mediawiki/oauthclient/src/Client.php on line 181
```

The URL had: https://patchdemo.wmflabs.org/?oauth_verifier=XXXX&oauth_token=YYYYY

I don't think I am logged in since the page still states _Sign in with OAuth to create and manage wikis._

**Comment by MatmaRex** [comment]
Presumably resolved by the fix in that task. Please reopen if you still see the problem.
