### ISSUE TITLE
Notice: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by Ammarpad** [MatmaRex/patchdemo#553]
Visiting https://patchdemo.wmflabs.org/ directly throws up these PHP notices

```
Notice: Trying to access array offset on value of type null in /var/www/html/includes.php on line 231

Notice: Trying to access array offset on value of type null in /var/www/html/includes.php on line 232
```

**Comment by MatmaRex** [comment]
I've seen this once or twice, but can't reproduce now.

The error points to the code querying Phabricator task titles. It might be failing when a patch refers to a non-existing task, or maybe a private task?

**Comment by Ammarpad** [comment]
I think that's correct. I  tested the API  and it return null for these cases.
