### ISSUE TITLE
Add WikiHiero extension

### ISSUE THREAD

**Issue by nikkiwd** [MatmaRex/patchdemo#588]
WikiHiero (https://www.mediawiki.org/wiki/Extension:WikiHiero) is used in Wikimedia projects to display hieroglyphs.

There is someone on the extension's talk page who is interested in contributing to the extension to improve the appearance of the hieroglyphs. I wanted to suggest using Patch demo so that people can test the changes, but the extension isn't listed.

**Comment by MatmaRex** [comment]
Done, sorry I haven't responded earlier.
