### ISSUE TITLE
"Proxy articles from wikipedia.org" option appears to be broken

### ISSUE THREAD

**Issue by NovemLinguae** [MatmaRex/patchdemo#589]
I checked this box when I created my patch demo, but visiting English Wikipedia article titles in the patch demo doesn't load the English Wikipedia article.

https://patchdemo.wmflabs.org/wikis/d94eddd976/w/index.php?title=Special:Search&search=Beyonc%C3%A9&wprov=acrw1_0

![image](https://github.com/MatmaRex/patchdemo/assets/79697282/70a503e1-3857-4d12-af4d-4e6bdf4e9e9f)

**Comment by edg2s** [comment]
I don't think Special:Search is supported by this feature. If you go straight to an article, e.g. https://patchdemo.wmflabs.org/wikis/d94eddd976/wiki/Dog the contents is proxied though.

If you think Special:Search should be supported, file a task on Phabricator.

**Comment by MatmaRex** [comment]
Yes, it's a little janky. This feature is provided by the MobileFrontendContentProvider extension, if you're looking for a place to complain ;)

https://www.mediawiki.org/wiki/Extension:MobileFrontendContentProvider
https://phabricator.wikimedia.org/project/view/5482/

**Comment by NovemLinguae** [comment]
Thanks. I filed https://phabricator.wikimedia.org/T344571
