### ISSUE TITLE
Customise [[Main Page]] content

### ISSUE THREAD

**Issue by edg2s** [MatmaRex/patchdemo#7]
It would probably be better if it said something like:

> This wiki was automatically generated by [https://github.com/MatmaRex/patchdemo patchdemo] at `datetime` and applies the following patches:
> * https://gerrit.wikimedia.org/...
> * ...
> 
> This wiki may be deleted in the near future so do not expect links to it to persist.

The main page is setup in `Installer.php#createMainpage`.

**Comment by MatmaRex** [comment]
It seems difficult to override that, but you could just edit it with `maintenance/edit.php` after creating the wiki.
