### ISSUE TITLE
Store OAuth credentials so session doesn't expire after 24 minutes

### ISSUE THREAD

**Issue by edg2s** [MatmaRex/patchdemo#75]

**Comment by DemianX0** [comment]
Between creating 2 wikis I often have to re-authenticate.
I haven't measured exactly, it might have taken between 10min - 1 hour to set up one wiki and finish (verify) the patch for the next.
In any case it feels like I have to auth too often.
A month or a week or infinite would be good for me, but doing many times a day does not seem a practical use of time, nor a security advantage.

Can this be adjusted?

**Comment by edg2s** [comment]
It looks like the credentials we get from OAuth are long term, so we wouldn't want to put those in a cookie.

We could just increase `session.gc_maxlifetime` to 24 hours on the server? Thoughts @MatmaRex?

(I don't think we can do this using `ini_set`, as Debian implements its own [PHP session GC](https://www.getpagespeed.com/server-setup/php/cleanup-php-sessions-like-a-pro) that reads the value from php.ini)

**Comment by MatmaRex** [comment]
Yeah, that sounds reasonable. The defaults are… really weird.

**Comment by MatmaRex** [comment]
Let's see if that fixes it, I applied the change on https://patchdemo.wmflabs.org/.

**Comment by DemianX0** [comment]
Thanks for fixing this!
