### ISSUE TITLE
OAuth TTL is short

### ISSUE THREAD

**Issue by DemianX0** [MatmaRex/patchdemo#79]
Between creating 2 wikis the I often have to re-authenticate.
I haven't measured exactly, it might have taken between 10min - 1 hour to set up one wiki and finish (verify) the patch for the next.
In any case it feels like I have to auth too often. 
A month or a week or infinite would be good for me, but doing many times a day does not seem a practical use of time, nor a security advantage.

Can this be adjusted?

**Comment by edg2s** [comment]
Duplicate of #75?

**Comment by DemianX0** [comment]
> Duplicate of #75?

Oh I'm sorry, I was lazy to look for it...
