### ISSUE TITLE
New Vector as default

### ISSUE THREAD

**Issue by DemianX0** [MatmaRex/patchdemo#80]
For development and demonstration it would be preferable to have the new Vector layout as default. 
LocalSettings:
```
$wgVectorDefaultSkinVersion = '2';
$wgVectorDefaultSkinVersionForExistingAccounts = '2'; // I guess this is not necessary.
$wgVectorDefaultSkinVersionForNewAccounts = '2';
```

**Comment by edg2s** [comment]
Given our production wikis are still running Vector 1 I think that's the most useful environment for most teams.

**Comment by edg2s** [comment]
Declined for the time being
